-- Persistent Quyền Locket website-user registry, login history and presence.
-- Idempotent so the Railway API can safely verify/apply it at startup.

CREATE TABLE IF NOT EXISTS web_users (
  uid TEXT PRIMARY KEY,
  internal_id UUID NOT NULL DEFAULT gen_random_uuid(),
  email TEXT,
  username TEXT,
  display_name TEXT,
  profile_picture TEXT,
  provider TEXT,
  disabled BOOLEAN NOT NULL DEFAULT FALSE,
  last_sign_in_at TIMESTAMPTZ,
  ip_address TEXT,
  browser TEXT,
  os TEXT,
  auth_provider TEXT NOT NULL DEFAULT 'locket-firebase',
  login_method TEXT NOT NULL DEFAULT 'unknown',
  account_status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  last_logout_at TIMESTAMPTZ,
  current_web_source TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE web_users ADD COLUMN IF NOT EXISTS internal_id UUID DEFAULT gen_random_uuid();
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS provider TEXT;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_sign_in_at TIMESTAMPTZ;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS browser TEXT;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS os TEXT;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'locket-firebase';
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS login_method TEXT DEFAULT 'unknown';
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS account_status TEXT DEFAULT 'active';
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_logout_at TIMESTAMPTZ;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS current_web_source TEXT;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE web_users
SET
  internal_id = COALESCE(internal_id, gen_random_uuid()),
  auth_provider = COALESCE(auth_provider, provider, 'locket-firebase'),
  login_method = COALESCE(login_method, 'unknown'),
  account_status = CASE WHEN COALESCE(disabled, FALSE) THEN 'locked' ELSE COALESCE(account_status, 'active') END,
  last_login_at = COALESCE(last_login_at, last_sign_in_at),
  last_seen_at = COALESCE(last_seen_at, last_sign_in_at),
  updated_at = COALESCE(updated_at, NOW());

CREATE UNIQUE INDEX IF NOT EXISTS web_users_internal_id_idx ON web_users (internal_id);
CREATE INDEX IF NOT EXISTS web_users_last_seen_idx ON web_users (last_seen_at DESC);
CREATE INDEX IF NOT EXISTS web_users_email_idx ON web_users (LOWER(email));

CREATE TABLE IF NOT EXISTS user_sessions (
  session_id UUID PRIMARY KEY,
  user_uid TEXT NOT NULL REFERENCES web_users(uid) ON DELETE CASCADE,
  web_source TEXT NOT NULL DEFAULT 'unknown',
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'active'
);

CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_uid, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS user_sessions_presence_idx ON user_sessions (status, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS login_history (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  uid TEXT NOT NULL,
  session_id UUID,
  ip_address TEXT,
  country TEXT,
  region TEXT,
  city TEXT,
  browser TEXT,
  browser_version TEXT,
  os TEXT,
  device TEXT,
  login_method TEXT,
  web_source TEXT,
  web_version TEXT,
  build_id TEXT,
  commit_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

ALTER TABLE login_history ADD COLUMN IF NOT EXISTS event_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS session_id UUID;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS browser_version TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_source TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_version TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS build_id TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS commit_hash TEXT;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS login_history_session_idx
  ON login_history (session_id) WHERE session_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS login_history_user_idx ON login_history (uid, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_uid TEXT NOT NULL,
  action TEXT NOT NULL,
  target_uid TEXT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx ON admin_audit_log (created_at DESC);
